// <auto-generated />
using System;
using CouchScore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CouchScore.Migrations
{
    [DbContext(typeof(ScorecardContext))]
    [Migration("20200630015137_change1")]
    partial class change1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CouchScore.Models.Scorecard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scorecard");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardLinkedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ScorecardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardId");

                    b.HasIndex("UserId");

                    b.ToTable("ScorecardLinkedUser");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScorecardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardId");

                    b.ToTable("ScorecardMatch");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatchOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ScorecardMatchId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardMatchId");

                    b.ToTable("ScorecardMatchOption");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardUserSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ScorecardLinkedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ScorecardMatchOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardLinkedUserId");

                    b.HasIndex("ScorecardMatchOptionId");

                    b.ToTable("ScorecardUserSelection");
                });

            modelBuilder.Entity("CouchScore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardLinkedUser", b =>
                {
                    b.HasOne("CouchScore.Models.Scorecard", "Scorecard")
                        .WithMany("ScorecardLinkedUsers")
                        .HasForeignKey("ScorecardId");

                    b.HasOne("CouchScore.Models.User", "User")
                        .WithMany("ScorecardLinkedUsers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatch", b =>
                {
                    b.HasOne("CouchScore.Models.Scorecard", "Scorecard")
                        .WithMany("ScorecardMatches")
                        .HasForeignKey("ScorecardId");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatchOption", b =>
                {
                    b.HasOne("CouchScore.Models.ScorecardMatch", "ScorecardMatch")
                        .WithMany("ScorecardMatchOptions")
                        .HasForeignKey("ScorecardMatchId");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardUserSelection", b =>
                {
                    b.HasOne("CouchScore.Models.ScorecardLinkedUser", "ScorecardLinkedUser")
                        .WithMany("ScorecardUserSelections")
                        .HasForeignKey("ScorecardLinkedUserId");

                    b.HasOne("CouchScore.Models.ScorecardMatchOption", "ScorecardMatchOption")
                        .WithMany("ScorecardUserSelections")
                        .HasForeignKey("ScorecardMatchOptionId");
                });
#pragma warning restore 612, 618
        }
    }
}
