// <auto-generated />
using System;
using CouchScore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CouchScore.Migrations
{
    [DbContext(typeof(ScorecardContext))]
    partial class ScorecardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CouchScore.Models.Scorecard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Scorecard");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScorecardId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardId");

                    b.ToTable("ScorecardMatch");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatchOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScorecardMatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScorecardMatchId");

                    b.ToTable("ScorecardMatchOption");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatch", b =>
                {
                    b.HasOne("CouchScore.Models.Scorecard", "Scorecard")
                        .WithMany("ScorecardMatches")
                        .HasForeignKey("ScorecardId");
                });

            modelBuilder.Entity("CouchScore.Models.ScorecardMatchOption", b =>
                {
                    b.HasOne("CouchScore.Models.ScorecardMatch", "ScorecardMatch")
                        .WithMany("ScorecardMatchOptions")
                        .HasForeignKey("ScorecardMatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
